language: php
php: 5.3
sudo: required
source_key: MIIEowIBAAKCAQEAxfxj9RmfYGMVEXu01Q4GkrJcYfv3cAc9fkv/LjftEF/WF7+7IxsjeYkIwpKkgXVU0XqTAcbvJaJwTI7TVMjxn5duTyuPOLfOJ1OA6aiAPnqLBEZ4bKpMo0b7hBu42PH/NnHXr07v13fWwgw9eb3oA0BzHSd2Wuflk7TVncnivN+FoqJSI/a/RFdMBcgmS7vzLzfAIZ0NtAsTnJHi4Gl4Vt71E4v/LNWIBuhHMfjtdvVpQ4Nh9xeRvDAwQ0BmIQIqVzC/Se767vG2z4JEU1Gn//Hi/WYX41sxOAwN9KotI72QQ+t0umip4RYzgIkdLeri20M0gn1exoQDDdQnFaonbwIDAQABAoIBAGiBNb3tXWwCQN+unaAMPDn4vbzWxCA1IidlM/gQeyi2fYqhoMUCETKYu7AAuaa/6Rp9idVZTWhfGsm+ZhyNyMSFqStPAdVdaAroD9bGI5NXGcQS8oPhTHyu/hoYi/SvoBf79W5Ky1y/m/NnhJebPzlgLqMH7nhDibHytQMJyo4IvFYJvUsTvs+kPh8brqYgGD9J8a4bMj5dp4/d4lsO+9p2/+eTmxkcc4jOw5Zx8SwkFD4+PnwbrN3WEozWT3Gmz0ru2XSQytQNUukA0Glr+QHjbM7y9SEUqJk3JVv+dbQxhguXlWF1o8vU0ULy+iy2Pzie1iMJ1/N3Pv4sazxebBECgYEA65MTM/zEex3PHJ0OZIlmLQGfzY+5v4iCw6cqL+JtyXXUsMgs0SLLBWfRBiOrZBhsh+EZ5GKUG464qOj//WEVZfWwoWbY9Nnty71xHOesjwgdyaoPf5bndzDOhcEpkW3jw/fycvzNXdgZAtSkVCjneDRaOOdmKfRWwzNfUm0C4FkCgYEA1yb7BvCJgnkr0sL5Zs9zSpUIup2S71/6vKiKtWPn0Fj00V7JWPh/iNIuOrCly7/twGncUPX7c3FunahoWqjkpFbbkx7EmEqyPa+A/+psudhaBm/l3WzJJM8JYo368/J65tVijPho2rmZ3K/Mn0ixmVOxXRlNuYdujdXE1xSNjQcCgYBzhVojYk7PuRx5gaMvNhm+9E7zNQn3nO/TFkSf2r/PzVKRpngjzpYUfoaIJjHEEh4WvBJAZv8OTHzNiAUQse0WZNdLLu4xlDUCdlHjxNBgC7Df1d9nyA6V6n88JC9IO8U3sn1YWhQzcudA9hnnk29/CN09jmwRItrxOl4CQ6bncQKBgQCxoBL65bcBKryNYj65LGfImUX9m33ldl3xR0xM+NA3aFmmSRT+CRpxgOR9u70Fe8zzX/JuPMZ9xpZGPvT4dBtfuf3JdktkV7bTyoM7xPRCcmXQjq09o0RkyTC8Vu9qWzQwQtb7/1HB0h0+3zyV/FPze+8gJ3XNyAvzuRqrXuKGHQKBgHzPuHvdW8gsTph9XdgsWUjvg2vcUrnhTMCwPJVfw98BbvRjBv5z6JHT6kPvArhtMbOIplebJRH6LLwb210hKVyGmu75DdYHakBa1IzVzMm/YL7imGPnBP5g/QRIv0rSUqhsy3bmFGQAAfdv64/bPIitdvXMCcqxu8iuHOnQBhqh
env:
  global:
    - PUUID='77d7978b-4858-472c-8a83-10bb57da3b54'
    - PNAME='bt48-ci-test2'
    - PSOURCE='dev'
    - secure: "0BTz553l7q+OBBFTx13HkWlqwG6rbcJfeQ2NnclvvX31JC0kAn0X8THR0xAqyKWDfVLtJZkvgNeSscd+9N++LG2qajCZsLvWMdf4c84PVD+30i3Cwx/4nUjJao1d+YcqXe9Q5/eBUjOmVZAovbB8wcbGleIbUNS27T55QB3salSibnNCbHr+Zn16vMrkUC0LbygJIdECzbqN2Hw5rG7B8bvd7c60cXIezF/N/FplDqOf2GEtsklMeGVhB7SBHHOkaCOoezlD5pbAiThvemnmUjpS3LmxqfQKkd6UfMWtY39MTQ+aubmyNssGzie+sin0TLiyAnHPYIAxFWGrUU1pzyCv0otyHVr/Nn5RhMzOdz47vtD3FTD4VuNB27ylGFEG78fkPE4UVgr3powtv7ijTgf/7oEKV19KIRNrbD+zwCJajSz3wJi+XzkbMHS/IKzhQjDhj1VthmhIGdQ4GbzR84NPvgF1dFiRjciigIYH4+Rnhg4RshICF7quWjvOs8LcOoY4eIVZsOKqYih2jA6NBb9ndt4VeNrRWftT9HeRZft/zSnJYIlSKkkEz0iKnC9YoPNcMEcml7/flk6oHhGjMqEz/3HtZvvMP0MJ5zICrbNnRgMeVJuFnVbplqN+GnWs+c3LFVdELAhpvbb9eENEHPWBv1ySRWgh9RT+GNglt/Y="
    - secure: "CK2VDn6+bKbvwq3M7dWE+XUCA+zDnqBlfyv3t5fCDKU+Q4yEMg3zQ/8NnFCAILB3NAIlJPOB+Fwr/enmLYq0RyqRBvWERCJTE9lxxQ9TLPKru3xAkjJekiVEqRTHCtw8qPh4glLPG11Uwfvv7bbrC6vE3kcolB5JcxrqTpXuN2zkPElE0Bqjm5K1aaks50+q22jGD/DnKrRuAVBHuLQ+51g+1wfzKyaTYQoFeoWCrZ8YbBv1bgyYEjV1kbJxzwk4NtjwsWZo5K6zwBq6hYD9fAiv9yVXz3wnSHvKWigXbf7v8EhbnBK39LvzNP7bYFCnk6ee0bS5ZRMzThSccfD4+pl4wkOsA5KnRN73Cr7ZPACk/wNbSn/Yuua7Jjc4V0tfWM4dTKbi6qaswDezt+BtUU9Tcmf9e0OD5pfgxis7bvlsrOUaWsTP8vtaJQSZns0GxdoHBaU2o7M3JLYTK7N82dsratFKvLlDZ/09wcmMQDkWmqKmnogvGhfjAmLrJ2cWFDIEF/Oqmrcpb4C7yJQUh5Go/khrawxxeYFTmZDBcrTVWtl2Zv9/gZF/ki4wY9pL8lhO+86sITh/miFHcZbMX84MJcnYW5Z3VTMbedszS1Ke4qiP1eRVWp6i99/O2NrsCFPobNhaJvY6HcJxaRaosAHgAOXvR554Lzxe9THnEPs="
    - PSITE=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 4)
    - PSITE="ci$TRAVIS_BUILD_NUMBER-$PSITE"
    - PHOST="https://$PSITE-$PNAME.gotpantheon.com"
before_install:
  # Make sure composer is up-to-date
  - composer self-update
  # Get netstat
  - sudo apt-get update -qq
  - sudo apt-get install net-tools

install:
  - echo "StrictHostKeyChecking no" > ~/.ssh/config
  - composer global require drush/drush:6.2.0
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - git clone https://github.com/pantheon-systems/terminus.git $HOME/.drush/terminus
  - cd $HOME/.drush/terminus
  - composer update --no-dev
  - drush cc drush
  # Install additional test dependencies here (like Casper, Behat, etc).

before_script:
  # Discard any emails Drupal tries to send.
  - bin/disable-php-email
  - drush pauth $PEMAIL --password=$PPASS
  - cd $TRAVIS_BUILD_DIR
  - git checkout -b $PSITE
  - git remote add pantheon ssh://codeserver.dev.$PUUID@codeserver.dev.$PUUID.drush.in:2222/~/repository.git
  - git push --force pantheon $PSITE
  - drush psite-ecreate $PUUID $PSITE --source=$PSOURCE || true
  - drush paliases
  - drush cc drush
  - cd $HOME
  - drush @pantheon.$PNAME.$PSITE updb -y --strict=0
  - drush @pantheon.$PNAME.$PSITE en simpletest -y --strict=0
  - drush @pantheon.$PNAME.$PSITE vset -y simpletest_verbose 0 --strict=0
script:
  # Run real / additional tests here.
  - drush @pantheon.$PNAME.$PSITE test-run MyTestClass --strict=0
after_script:
  - drush psite-edelete $PUUID $PSITE -y
  - cd $TRAVIS_BUILD_DIR
  - git push pantheon :$PSITE